export const listOfItems = [
    {
        "heading": "ארונות ושידות",
    "subheading": [
        {"name": "ארון 2 דלתות", "price": 300, "disassembly_costs": 100},
        {"name": "ארון 3 דלתות", "price": 350, "disassembly_costs": 150},
        {"name": "ארון 4 דלתות", "price": 400, "disassembly_costs": 200},
        {"name": "ארון 5 דלתות", "price": 450, "disassembly_costs": 250},
        {"name": "ארון 6 דלתות", "price": 500, "disassembly_costs": 300},
        {"name": "ארון הזזה 2 דלתות", "price": 350, "disassembly_costs": 150},
        {"name": "ארון הזזה 3 דלתות", "price": 400, "disassembly_costs": 200},
        {"name": "ארון הזזה 4 דלתות", "price": 450, "disassembly_costs": 250},
        {"name": "ארון הזזה 5 דלתות", "price": 500, "disassembly_costs": 300},
        {"name": "ארון ויטרינה", "price": 300, "disassembly_costs": 100},
        {"name": "ארון כתר", "price": 200, "disassembly_costs": 75},
        {"name": "ארונית מדפים", "price": 200, "disassembly_costs": 100},
        {"name": "כוורת עד 6 תאים", "price": 200, "disassembly_costs": 75},
        {"name": "כוורת עד 10 תאים", "price": 300, "disassembly_costs": 125},
        {"name": "כוורת עד 12 תאים", "price": 450, "disassembly_costs": 175},
        {"name": "שידה עם מראה", "price": 300, "disassembly_costs": 100},
        {"name": "שידת החתלה", "price": 200, "disassembly_costs": 100},
        {"name": "שידה עד 3 שלבים", "price": 200, "disassembly_costs": 75},
        {"name": "שידה עד 5 שלבים", "price": 250, "disassembly_costs": 100},
        {"name": "שידה כפולה עד 3 שלבים", "price": 300, "disassembly_costs": 150},
        {"name": "שידה כפולה עד 6 שלבים", "price": 350, "disassembly_costs": 200},
        {"name": "ספרייה עד 2 מטר", "price": 350, "disassembly_costs": 150},
        {"name": "ספרייה עד 4 מטר", "price": 450, "disassembly_costs": 225},
        {"name": "ספרייה עד 6 מטר", "price": 600, "disassembly_costs": 300}
    ]
},
    {
       "heading": "מיטות ומזרנים",
    "subheading": [
        { "name": "מיטה זוגית רגילה", "price": 300, "disassembly_costs": 75 },
        { "name": "מיטה זוגית עם מנגנון/ארגז", "price": 400, "disassembly_costs": 175 },
        { "name": "מיטה זוגית קינג סייז", "price": 400, "disassembly_costs": 100 },
        { "name": "מיטה וחצי", "price": 300, "disassembly_costs": 75 },
        { "name": "מיטה וחצי עם מנגנון/ארגז", "price": 400, "disassembly_costs": 175 },
        { "name": "מיטת יחיד", "price": 250, "disassembly_costs": 75 }, 
        { "name": "מיטת יחיד נפתחת/ארגז", "price": 350, "disassembly_costs": 125 },
        { "name": "מיטת ילד", "price": 200, "disassembly_costs": 50 },
        { "name": "מיטת קומותיים", "price": 400, "disassembly_costs": 175 },
        { "name": "מיטה יהודית", "price": 500, "disassembly_costs": 150 },
        { "name": "לול תינוק", "price": 150, "disassembly_costs": 100 },
        { "name": "מזרן זוגי", "price": 150, "disassembly_costs": 0 },
        { "name": "מזרן זוגי קינג סייז", "price": 200, "disassembly_costs": 0 },
        { "name": "מזרן יחיד", "price": 100, "disassembly_costs": 0 },
        { "name": "מזרן יחיד דק", "price": 50, "disassembly_costs": 0 },
        { "name": "מזרן ילדים", "price": 50, "disassembly_costs": 0 },
        { "name": "בסיס מיטה זוגית", "price": 200, "disassembly_costs": 75 },
        { "name": "בסיס מיטה שלבים", "price": 150, "disassembly_costs": 75 }
        ]
    },
        {
       "heading": "שולחנות וכיסאות",
    "subheading": [
        { "name": "שולחן אוכל 2 כסאות", "price": 300, "disassembly_costs": 100 },
        { "name": "שולחן אוכל 4 כסאות", "price": 400, "disassembly_costs": 150 },
        { "name": "שולחן אוכל 6 כסאות", "price": 500, "disassembly_costs": 200 },
        { "name": "שולחן אוכל 8 כסאות", "price": 600, "disassembly_costs": 250 },
        { "name": "שולחן אוכל רגיל (ללא כסאות)", "price": 250, "disassembly_costs": 100 },
        { "name": "שולחן אוכל גדול (ללא כסאות)", "price": 400, "disassembly_costs": 150 },
        { "name": "שולחן אוכל גדול מאוד (ללא כסאות)", "price": 600, "disassembly_costs": 200 },
        { "name": "שולחן סלון רגיל", "price": 200, "disassembly_costs": 100 },
        { "name": "שולחן סלון כבד (ברזל/עץ מלא)", "price": 300, "disassembly_costs": 150 },
        { "name": "שולחן גינה קטן", "price": 100, "disassembly_costs": 75 },
        { "name": "שולחן גינה בינוני", "price": 150, "disassembly_costs": 100 },
        { "name": "שולחן גינה גדול", "price": 200, "disassembly_costs": 125 },
        { "name": "שולחן מחשב רגיל", "price": 200, "disassembly_costs": 75 },
        { "name": "שולחן מחשב עם כנף/כוורת", "price": 300, "disassembly_costs": 125 },
        { "name": "שולחן מחשב עם כוורת וכנף", "price": 400, "disassembly_costs": 175 },
        { "name": "שולחן משרדי", "price": 400, "disassembly_costs": 175 },
        { "name": "שולחן נוי רגיל", "price": 150, "disassembly_costs": 75 },
        { "name": "שולחן נוי כבד (ברזל/עץ מלא)", "price": 250, "disassembly_costs": 100 },
        { "name": "כסא עץ", "price": 50, "disassembly_costs": 50 },
        { "name": "כסא פלסטיק", "price": 20, "disassembly_costs": 0 },
        { "name": "שרפשרף", "price": 20, "disassembly_costs": 0 },
        { "name": "כסא בר", "price": 50, "disassembly_costs": 50 },
        { "name": "כסא תינוק", "price": 30, "disassembly_costs": 50 },
        { "name": "כסא מחשב רגיל", "price": 50, "disassembly_costs": 50 },
        { "name": "כסא מנהלים", "price": 70, "disassembly_costs": 75 }
        ]
        },
    {
        "heading": "ספות וכורסאות",
    "subheading": [
        { "name": "ספה 2 מושבים", "price": 250, "disassembly_costs": 75 },
        { "name": "ספה 3 מושבים", "price": 300, "disassembly_costs": 100 },
        { "name": "ספה 2 מושבים עם מנגנון", "price": 400, "disassembly_costs": 125 },
        { "name": "ספה 3 מושבים עם מנגנון", "price": 450, "disassembly_costs": 175 },
        { "name": "ספה ריש", "price": 400, "disassembly_costs": 100 },
        { "name": "ספה ריש גדולה", "price": 450, "disassembly_costs": 125 },
        { "name": "ספה + שזלונג", "price": 450, "disassembly_costs": 125 },
        { "name": "שזלונג", "price": 150, "disassembly_costs": 50 },
        { "name": "ספה נפתחת", "price": 400, "disassembly_costs": 125 },
        { "name": "כורסא יחיד", "price": 100, "disassembly_costs": 50 },
        { "name": "כורסא גדולה", "price": 150, "disassembly_costs": 75 },
        { "name": "כורסא נפתחת/מנגנון", "price": 200, "disassembly_costs": 100 },
        { "name": "כורסת עיסוי", "price": 300, "disassembly_costs": 125 }
     ]
    },
    {
        "heading": "מוצרי חשמל",
    "subheading": [
        { "name": "מקרר 2 דלתות", "price": 500, "disassembly_costs": 100 },
        { "name": "מקרר עד 300 ליטר", "price": 300, "disassembly_costs": 100 },
        { "name": "מקרר עד 500 ליטר", "price": 450, "disassembly_costs": 150 },
        { "name": "מקרר כפול (4 דלתות)", "price": 600, "disassembly_costs": 200 },
        { "name": "מקרר משרדי/מיני בר", "price": 100, "disassembly_costs": 50 },
        { "name": "מקפיא עד 6 מדפים", "price": 200, "disassembly_costs": 100 },
        { "name": "כיריים", "price": 50, "disassembly_costs": 75 },
        { "name": "מדיח כלים", "price": 300, "disassembly_costs": 100 },
        { "name": "תנור בילד אין", "price": 300, "disassembly_costs": 100 },
        { "name": "תנור + כיריים", "price": 350, "disassembly_costs": 125 },
        { "name": "תנור גדול", "price": 400, "disassembly_costs": 125 },
        { "name": "קולט אדים ביתי", "price": 250, "disassembly_costs": 125 },
        { "name": "מייבש כביסה", "price": 400, "disassembly_costs": 100 },
        { "name": "מכונת כביסה", "price": 400, "disassembly_costs": 125 },
        { "name": "שואב אבק", "price": 150, "disassembly_costs": 100 },
        { "name": "טוסטר אובן", "price": 100, "disassembly_costs": 50 },
        { "name": "מיקרוגל", "price": 50, "disassembly_costs": 50 },
        { "name": "מכונת קפה", "price": 50, "disassembly_costs": 50 },
        { "name": "מתקן מים עומד כולל מיכל אחד", "price": 150, "disassembly_costs": 75 },
        { "name": "מתקן מים שולחני/תמי 4", "price": 100, "disassembly_costs": 75 },
        { "name": "טלויזיה 30-60 אינץ'", "price": 250, "disassembly_costs": 100 },
        { "name": "טלויזיה 60-80 אינץ'", "price": 350, "disassembly_costs": 125 },
        { "name": "מקרן כולל מסך הקרנה", "price": 150, "disassembly_costs": 100 },
        { "name": "מחשב נייח", "price": 250, "disassembly_costs": 100 },
        { "name": "מדפסת ביתית/פקס", "price": 150, "disassembly_costs": 75 },
        { "name": "מאוורר ביתי", "price": 50, "disassembly_costs": 25 },
        { "name": "מזגן נייד", "price": 250, "disassembly_costs": 125 },
        { "name": "מזגן + מדחס חיצוני עד 2 כוחות סוס", "price": 450, "disassembly_costs": 350 },
        { "name": "מזגן + מדחס חיצוני מעל 2 כוחות סוס", "price": 550, "disassembly_costs": 500 },
        { "name": "רדיאטור", "price": 150, "disassembly_costs": 50, },
        { "name": "תנור חימום/נפט", "price": 150, "disassembly_costs": 50 },
        { "name": "גריל מנגל חשמלי סטנדרטי", "price": 350, "disassembly_costs": 100 },
        { "name": "גריל מנגל חשמלי גדול", "price": 450, "disassembly_costs": 125 },
        ]   
    },
]   