export const listOfItems = [
    {
        heading: 'Wardrobes and Dressers',
        subheading: [
            { name: "2-door Wardrobe", price: 300 },
            { name: "3-door Wardrobe", price: 350 },
            { name: "4-door Wardrobe", price: 400 },
            { name: "5-door Wardrobe", price: 450 },
            { name: "6-door Wardrobe", price: 500 },
            { name: "2-door Sliding Wardrobe", price: 350 },
            { name: "3-door Sliding Wardrobe", price: 400 },
            { name: "4-door Sliding Wardrobe", price: 450 },
            { name: "5-door Sliding Wardrobe", price: 500 },
            { name: "Display Cabinet", price: 300 },
            { name: "Crown Wardrobe", price: 200 },
            { name: "Shelf Unit", price: 200 },
            { name: "Hive up to 6 cells", price: 200 },
            { name: "Hive up to 10 cells", price: 300 },
            { name: "Hive up to 12 cells", price: 450 },
            { name: "Dresser with Mirror", price: 300 },
            { name: "Changing Dresser", price: 200 },
            { name: "Dresser up to 3 drawers", price: 200 },
            { name: "Dresser up to 5 drawers", price: 250 },
            { name: "Double Dresser up to 3 drawers", price: 300 },
            { name: "Double Dresser up to 6 drawers", price: 350 },
            { name: "Library up to 2 meters", price: 350 },
            { name: "Library up to 4 meters", price: 450 },
            { name: "Library up to 6 meters", price: 600 },
        ]
    },
    {
        heading: 'Beds and Mattresses',
        subheading: [
            { name: "Standard Double Bed", price: 300 },
            { name: "Double Bed with Mechanism/Storage", price: 400 },
            { name: "King Size Double Bed", price: 400 },
            { name: "Semi Double Bed", price: 300 },
            { name: "Semi Double Bed with Mechanism/Storage", price: 400 },
            { name: "Single Bed", price: 250 },
            { name: "Single Bed with Folding/Storage", price: 350 },
            { name: "Child's Bed", price: 200 },
            { name: "Bunk Bed", price: 400 },
            { name: "Jewish Bed", price: 500 },
            { name: "Baby Cradle", price: 150 },
            { name: "Double Mattress", price: 150 },
            { name: "King Size Double Mattress", price: 200 },
            { name: "Single Mattress", price: 100 },
            { name: "Thin Single Mattress", price: 50 },
            { name: "Children's Mattress", price: 50 },
            { name: "Double Bed Base", price: 200 },
            { name: "Staged Bed Base", price: 150 },
        ]
    },
    {
        heading: 'Tables and Chairs',
        subheading: [
            { name: "Dining Table 2 Chairs", price: 300 },
            { name: "Dining Table 4 Chairs", price: 400 },
            { name: "Dining Table 6 Chairs", price: 500 },
            { name: "Dining Table 8 Chairs", price: 600 },
            { name: "Regular Dining Table (no chairs)", price: 250 },
            { name: "Large Dining Table (no chairs)", price: 400 },
            { name: "Very Large Dining Table (no chairs)", price: 600 },
            { name: "Regular Coffee Table", price: 200 },
            { name: "Heavy Coffee Table (Iron/Solid Wood)", price: 300 },
            { name: "Small Garden Table", price: 100 },
            { name: "Medium Garden Table", price: 150 },
            { name: "Large Garden Table", price: 200 },
            { name: "Regular Computer Desk", price: 200 },
            { name: "Computer Desk with Wing/Cubicles", price: 300 },
            { name: "Computer Desk with Cubicles and Wing", price: 400 },
            { name: "Office Desk", price: 400 },
            { name: "Regular Ornamental Table", price: 150 },
            { name: "Heavy Ornamental Table (Iron/Solid Wood)", price: 250 },
            { name: "Wooden Chair", price: 50 },
            { name: "Plastic Chair", price: 20 },
            { name: "Step Stool", price: 20 },
            { name: "Bar Stool", price: 50 },
            { name: "Baby Chair", price: 30 },
            { name: "Regular Computer Chair", price: 50 },
            { name: "Executive Chair", price: 70 },
        ]
    },
    {
        heading: 'Sofas and Armchairs',
        subheading: [
            { name: "2-seat Sofa", price: 250 },
            { name: "3-seat Sofa", price: 300 },
            { name: "2-seat Sofa with Mechanism", price: 400 },
            { name: "3-seat Sofa with Mechanism", price: 450 },
            { name: "Reese Sofa", price: 400 },
            { name: "Large Reese Sofa", price: 450 },
            { name: "Sofa + Chaise Lounge", price: 450 },
            { name: "Chaise Lounge", price: 150 },
            { name: "Fold-out Sofa", price: 400 },
            { name: "Single Armchair", price: 100 },
            { name: "Large Armchair", price: 150 },
            { name: "Fold-out Armchair/Mechanism", price: 200 },
            { name: "Massage Armchair", price: 300 },
        ]
    },
    {
        heading: 'Electrical Appliances',
        subheading: [
            { name: "2-door Refrigerator", price: 500 },
            { name: "Refrigerator up to 300 Liters", price: 300 },
            { name: "Refrigerator up to 500 Liters", price: 450 },
            { name: "Double (4-door) Refrigerator", price: 600 },
            { name: "Office/Mini Bar Refrigerator", price: 100 },
            { name: "Freezer up to 6 shelves", price: 200 },
            { name: "Stovetop", price: 50 },
            { name: "Dishwasher", price: 300 },
            { name: "Built-in Oven", price: 300 },
            { name: "Oven + Stovetop", price: 350 },
            { name: "Large Oven", price: 400 },
            { name: "Home Hood", price: 250 },
            { name: "Clothes Dryer", price: 400 },
            { name: "Washing Machine", price: 400 },
            { name: "Vacuum Cleaner", price: 150 },
            { name: "Toaster Oven", price: 100 },
            { name: "Microwave", price: 50 },
            { name: "Coffee Machine", price: 50 },
            { name: "Standing Water Cooler including one bottle", price: 150 },
            { name: "Tabletop Water Cooler/Tami 4", price: 100 },
            { name: "TV 30-60 inches", price: 250 },
            { name: "TV 60-80 inches", price: 350 },
            { name: "Projector including projection screen", price: 150 },
            { name: "Desktop Computer", price: 250 },
            { name: "Home Printer/Fax", price: 150 },
            { name: "Home Fan", price: 50 },
            { name: "Portable Air Conditioner", price: 250 },
            { name: "Air Conditioner + External Compressor up to 2 HP", price: 450 },
            { name: "Air Conditioner + External Compressor over 2 HP", price: 550 },
            { name: "Radiator", price: 150 },
            { name: "Heater/Oil Radiator", price: 150 },
            { name: "Standard Electric Grill", price: 350 },
            { name: "Large Electric Grill", price: 450 }
        ]
    }
];

